# Generated by Django 4.2.6 on 2023-11-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='country',
            field=models.CharField(choices=[('india', 'india'), ('America', 'America'), ('China', 'China')], default='India', max_length=20),
        ),
    ]
