# Generated by Django 4.2.6 on 2023-11-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='district',
            field=models.CharField(choices=[('anantnag', 'anantnag'), ('udupi', 'udupi'), ('baramullah', 'baramullah')], default='udupi', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('karnataka', 'karnataka'), ('hyderabad', 'hyderabad'), ('jammu and kashmir', 'jammu and kashmir')], default='karnataka', max_length=20),
        ),
    ]
