# Generated by Django 4.2.6 on 2023-11-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_district_item_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='village',
            field=models.CharField(default='karkala', max_length=20),
        ),
    ]
